"""empty message

Revision ID: dd6b52653503
Revises: 
Create Date: 2022-11-24 12:04:14.413645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6b52653503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('booktitle', sa.String(length=50), nullable=True),
    sa.Column('bookauthor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('bookid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
